name: liquid_loader
description: This library adds a liquid loading effect to your screen. Use it as a loading indicator, progress tracker, or any measurement tool.
version: 0.0.6

homepage: https://github.com/mfarooqone/liquid_loader
repository: https://github.com/mfarooqone/liquid_loader

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_parsing: ^1.1.0
  auto_size_text: ^3.0.0
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
